<div id="page-heading"><h1>Cadastro de Fornecedores</h1></div>
<div id="message-red" <?php echo $this->mErro;?>>
<table border="0" width="100%" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td class="red-left">Erro: Favor digitar todos campos obrigatórios.</td>
			<td class="red-right"><a class="close-red"><img src="<?php echo $this->baseUrl('images/table/icon_close_red.gif');?>" alt=""></a></td>
</tr>
</tbody></table>
</div>
<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
	<tr>	
		<th rowspan="3" class="sized"><img src="<?php echo $this-> baseUrl('images/shared/side_shadowleft.jpg');?>" width="20" height="300" alt="" /></th>
		
		<th class="topleft"></th>
		
		<td id="tbl-border-top">&nbsp;</td>
		
		<th class="topright"></th>
		
		<th rowspan="3" class="sized"><img src="<?php echo $this-> baseUrl('images/shared/side_shadowright.jpg');?>" width="20" height="300" alt="" /></th>
	
	</tr>
	
	<tr>
	
		<td id="tbl-border-left"></td>
	
		<td>
	
			<!--  start content-table-inner ...................................................................... START -->
			
			<div id="content-table-inner">
						
				<!--  start table-content  -->
				
				<div id="table-content">
			
		
					<?php 
						echo $this->form;
					?>
				</div>
	
				<!--  end content-table  -->
			</div>
		</td>
		<td id="tbl-border-right"></td>
	</tr>
	<tr>

		<th class="sized bottomleft"></th>

		<td id="tbl-border-bottom">&nbsp;</td>

		<th class="sized bottomright"></th>

	</tr>

</table>
