
<div id="page-heading">
    <h1><?php echo $this->titulo; ?></h1>
</div>

<div id="btn_acao_topo">
    <span>
        <a href="<?php echo $this->url(array('controller' => 'condicao-pagamento', 'module' => 'admin', 'action' => 'index')); ?>">Voltar</a>
    </span>
</div>

<?php if (count($this->form->getMessages()) > 0) { ?>
<div id="message-red">
    <table border="0" width="97%" cellpadding="0" cellspacing="0" style="margin: 0 auto;">
        <tr>
            <td class="red-left">Erro: Favor digitar todos campos obrigatórios</td>
            <td class="red-right"><a class="close-red"><img src="<?php echo $this->baseUrl('images/table/icon_close_red.gif'); ?>"   alt="" /></a></td>
        </tr>
    </table>
</div>
<?php } ?>

<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
    <?php echo $this->form->condicao_pagamento->renderViewHelper(); ?>
    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">

        <tr>
            <th rowspan="3" class="sized"><img src="<?php echo $this->baseUrl('images/shared/side_shadowleft.jpg'); ?>" width="20" height="300" alt="" /></th>
            <th class="topleft"></th>
            <td id="tbl-border-top">&nbsp;</td>
            <th class="topright"></th>
            <th rowspan="3" class="sized"><img src="<?php echo $this->baseUrl('images/shared/side_shadowright.jpg'); ?>" width="20" height="300" alt="" /></th>
        </tr>
        <tr>
            <td id="tbl-border-left"></td>
            <td>
                <!--  start content-table-inner -->



                <div id="content-table-inner">

                    <table border="0" width="100%" cellpadding="0" cellspacing="0">

                        <tr valign="top">
                            <td>
                                <!-- start id-form -->
                                <table border="0" cellpadding="0" cellspacing="0"  id="id-form">

                                    <tr>
                                        <th valign="top"><?php echo $this->form->codigo->renderLabel(); ?></th>
                                        <td><?php echo $this->form->codigo->renderViewHelper(); ?></td>
                                        <td>
                                            <?php if ($this->form->codigo->renderErrors()) { ?>
                                                <div class="error-left"></div>
                                                <div class="error-inner">
                                                    <?php echo $this->form->codigo->renderErrors(); ?>
                                                </div>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th valign="top"><?php echo $this->form->descricao->renderLabel(); ?></th>
                                        <td>
                                            <?php echo $this->form->descricao->renderViewHelper(); ?>
                                            <!-- <input type="text" class="inp-form-error" />-->
                                        </td>
                                        <td>
                                            <?php if ($this->form->descricao->renderErrors()) { ?>
                                                <div class="error-left"></div>
                                                <div class="error-inner">
                                                    <?php echo $this->form->descricao->renderErrors(); ?>
                                                </div>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th valign="top"><?php echo $this->form->ativo->renderLabel(); ?></th>
                                        <td>
                                            <?php echo $this->form->ativo->renderViewHelper(); ?>
                                            <!-- <input type="text" class="inp-form-error" />-->
                                        </td>
                                        <td>
                                            <?php if ($this->form->ativo->renderErrors()) { ?>
                                                <div class="error-left"></div>
                                                <div class="error-inner">
                                                    <?php echo $this->form->ativo->renderErrors(); ?>
                                                </div>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>&nbsp;</th>
                                        <td valign="top">
                                            <input type="submit" value="" class="form-submit" />
                                            <input type="reset" value="" class="form-reset"  />
                                        </td>
                                        <td></td>
                                    </tr>
                                </table>
                                <!-- end id-form  -->

                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><img src="<?php echo $this->baseUrl('images/shared/blank.gif'); ?>" width="695" height="1" alt="blank" /></td>
                            <td></td>
                        </tr>
                    </table>

                    <div class="clear"></div>


                </div>
                <!--  end content-table-inner  -->
            </td>
            <td id="tbl-border-right"></td>
        </tr>
        <tr>
            <th class="sized bottomleft"></th>
            <td id="tbl-border-bottom">&nbsp;</td>
            <th class="sized bottomright"></th>
        </tr>
    </table>
</form>
