<div id="page-heading"><h1>Nova Peça</h1></div>
<div id="message-red" <?php echo $this->mErro;?>>
<table border="0" width="100%" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td class="red-left">Erro: Favor digitar todos campos obrigatórios.</td>
			<td class="red-right"><a class="close-red"><img src="<?php echo $this->baseUrl('images/table/icon_close_red.gif');?>" alt=""></a></td>
</tr>
</tbody></table>
</div>
<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
			<?php 
		echo $this->form;
		?>
</table>


