<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">

	<tr>

		<th rowspan="3" class="sized"><img src="<?php echo $this-> baseUrl('images/shared/side_shadowleft.jpg');?>" width="20" height="300" alt="" /></th>

		<th class="topleft"></th>

		<td id="tbl-border-top">&nbsp;</td>

		<th class="topright"></th>

		<th rowspan="3" class="sized"><img src="<?php echo $this-> baseUrl('images/shared/side_shadowright.jpg');?>" width="20" height="300" alt="" /></th>

	</tr>

	<tr>

		<td id="tbl-border-left"></td>

		<td>

		<!--  start content-table-inner ...................................................................... START -->

		<div id="content-table-inner">

		

			<!--  start table-content  -->

			<div id="table-content">

			

				<!--  start message-yellow -->

			<form id="mainform" action="<?php echo $this->url(array('controller' => 'peca', 'module' => 'admin', 'action' => 'etiqueta')); ?>" method='post'>
			<table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
			<tr>
			<th class="table-header-check"><a id="toggle-all" ></a> </th>
			<th class="table-header-repeat line-left minwidth-1"><a href="">referencia</a>	</th>
			<th class="table-header-repeat line-left minwidth-1"><a href="">descricao</a></th>
			<th class="table-header-repeat line-left"><a href="">unidade</a></th>
			<th class="table-header-repeat line-left"><a href="">origem</a></th>
			<th class="table-header-repeat line-left"><a href="">ipi</a></th>
			<th class="table-header-options line-left"><a href="">Options</a></th>
			</tr>
			
			<?php
			 
			foreach ($this->paginator as $i => $p) {
				
			?>
			<tr>
			<td><input type="checkbox" name="<?php echo $i;?>" value="<?php echo $p['referencia'];?>"></td>
			<td><?php echo $p['referencia'];?></td>
			<td><?php echo $p['descricao'];?></td>
			<td><?php echo $p['unidade'];?></td>
			<td><?php echo $p['origem'];?></td>
			<td><?php echo $p['ipi'];?></td>
			<td class="options-width">
				<a href="<?php echo $this->url(array('controller' => 'peca', 'module' => 'admin', 'action' => 'editar','id' => $p['peca'])); ?>" title="Edit" class="icon-1 info-tooltip"></a>
				<a href="" title="Edit" class="icon-2 info-tooltip"></a>
				<a href="" title="Edit" class="icon-3 info-tooltip"></a>
				<a href="" title="Edit" class="icon-4 info-tooltip"></a>
				<a href="" title="Edit" class="icon-5 info-tooltip"></a>
			</td>
			</tr>
			<?php 
			}
			
			?>
		</table>
		</div>

			<!--  end content-table  -->

		

			<!--  start actions-box ............................................... -->

			<div id="actions-box">

				<a href="" class="action-slider"></a>

				<div id="actions-box-slider">

					<a href="" class="action-edit">Edit</a>

					<a href="" class="action-delete">Delete</a>
					<a href="javascript: mainform.submit();" class="action-edit">Gerar Etiquetas</a>					

				</div>

				<div class="clear"></div>

			</div>
	
			<!-- end actions-box........... -->

		<?php echo $this->paginationControl($this->paginator, 'Sliding','paginacao.phtml'); ?>
			

			<div class="clear"></div>

		 

		</div>
	</form>
		<!--  end content-table-inner ............................................END  -->

		</td>

		<td id="tbl-border-right"></td>

	</tr>

	<tr>

		<th class="sized bottomleft"></th>

		<td id="tbl-border-bottom">&nbsp;</td>

		<th class="sized bottomright"></th>

	</tr>

	</table>

	<div class="clear">&nbsp;</div>